name: container
on:
  push:
    branches: [main]

jobs:
   job1:
      runs-on: ubuntu-latest
      container:
        image: ghcr.io/sindhu530/nodejs:latest
        credentials:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
      steps:
        - name: printing
          run: echo "hi"

      

  
          
