name: Auto-PR
on:
  push:
    branches: ['feature']

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout
      
    - name: Raise PR 
      uses: peter-evans/create-pull-request@v3
      with:
          branch: "develop"
          base: feature
          title: "auto PR from feature into develop"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            PR creation
          token: ${{ secrets.GITHUB_TOKEN }}
          
     
