on:
  push:
    branches: develop
    
name: create-pull-request workflow
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Add report file
          title: 'PR to main'
         
          
