name: Auto-PR
on:
  push:
    branches: ['develop']

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout
      
    - name: extract git commit data
      uses: rlespinasse/git-commit-data-action@v1.x

    - name: Update author information
      run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR
     

    - name: Raise PR 
      uses: peter-evans/create-pull-request@v3
      with:
          branch: "main"
          base: develop
          title: "auto PR from develop to main"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            PR creation
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
     
