name: Auto-PR
on:
  push:
    branches: ['feature']

jobs:
  pull-request:
    name: Open PR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout
      
    - name: extract git commit data
      uses: rlespinasse/git-commit-data-action@v1.x

    - name: Update author information
      run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR
     
    - uses: repo-sync/pull-request@v2
      name: pull-request from develop to main
      with:
          destination_branch: "develop"
          pr_title: "auto PR from ${{ github.ref }} into develop"
          pr_body: " Automated PR*"
          pr_reviewer: "sindhu"
          pr_draft: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
     
