on:
  push:
    branches: feature
    
name: create-pull-request workflow
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2
        
      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

     

      - name: Raise PR 
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "develop"
          base: feature
          title: "auto PR from feature into develop"
          body:
            PR creation
          token: ${{ secrets.GITHUB_TOKEN }}
          
